"""add_ai_call_logs

Revision ID: 493e8070e91a
Revises: eec4365090c8
Create Date: 2026-05-27 08:27:37.317092

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '493e8070e91a'
down_revision: Union[str, Sequence[str], None] = 'eec4365090c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_call_logs',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('claim_id', sa.Uuid(), nullable=True),
    sa.Column('policy_id', sa.Uuid(), nullable=True),
    sa.Column('service', sa.String(length=100), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['policy_id'], ['policies.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_call_logs_claim_id'), 'ai_call_logs', ['claim_id'], unique=False)
    op.create_index(op.f('ix_ai_call_logs_policy_id'), 'ai_call_logs', ['policy_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_call_logs_policy_id'), table_name='ai_call_logs')
    op.drop_index(op.f('ix_ai_call_logs_claim_id'), table_name='ai_call_logs')
    op.drop_table('ai_call_logs')
    # ### end Alembic commands ###
