"""initial_schema

Revision ID: eec4365090c8
Revises: 5d46d33b6768
Create Date: 2026-05-27 08:02:09.527339

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'eec4365090c8'
down_revision: Union[str, Sequence[str], None] = '5d46d33b6768'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Create enum types explicitly first
    postgresql.ENUM('customer', 'insurer_officer', 'advisor', 'aggregator', 'admin', name='user_role_enum').create(op.get_bind(), checkfirst=True)
    postgresql.ENUM('comprehensive', 'third_party', 'standalone_od', name='policy_type_enum').create(op.get_bind(), checkfirst=True)
    postgresql.ENUM('active', 'expired', 'cancelled', name='policy_status_enum').create(op.get_bind(), checkfirst=True)
    postgresql.ENUM('own_damage', 'third_party', 'theft', 'natural_calamity', 'fire', name='claim_type_enum').create(op.get_bind(), checkfirst=True)
    postgresql.ENUM('draft', 'submitted', 'under_review', 'surveyor_assigned', 'approved', 'rejected', 'settled', 'disputed', name='claim_status_enum').create(op.get_bind(), checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('advisor_assignments',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('advisor_id', sa.Uuid(), nullable=False),
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('granted_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['advisor_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_advisor_assignments_advisor_id'), 'advisor_assignments', ['advisor_id'], unique=False)
    op.create_index(op.f('ix_advisor_assignments_customer_id'), 'advisor_assignments', ['customer_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(length=255), nullable=False),
    sa.Column('resource_type', sa.String(length=100), nullable=False),
    sa.Column('resource_id', sa.Uuid(), nullable=True),
    sa.Column('before_state', sa.JSON(), nullable=True),
    sa.Column('after_state', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_actor_id'), 'audit_logs', ['actor_id'], unique=False)
    op.create_table('consent_records',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('consent_type', sa.Enum('data_processing', 'marketing', 'ai_analysis', 'third_party_sharing', name='consent_type_enum'), nullable=False),
    sa.Column('granted', sa.Boolean(), nullable=False),
    sa.Column('granted_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('ip_address', sa.String(length=100), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consent_records_user_id'), 'consent_records', ['user_id'], unique=False)
    op.create_table('claim_images',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('claim_id', sa.Uuid(), nullable=False),
    sa.Column('uploaded_by', sa.Uuid(), nullable=False),
    sa.Column('storage_path', sa.String(length=500), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=False),
    sa.Column('ai_damage_tags', sa.JSON(), nullable=True),
    sa.Column('ai_damage_confidence', sa.Float(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_claim_images_claim_id'), 'claim_images', ['claim_id'], unique=False)
    op.create_index(op.f('ix_claim_images_uploaded_by'), 'claim_images', ['uploaded_by'], unique=False)
    op.create_table('conversations',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('policy_id', sa.Uuid(), nullable=True),
    sa.Column('claim_id', sa.Uuid(), nullable=True),
    sa.Column('context_type', sa.Enum('policy_qa', 'claim_guidance', 'general', name='context_type_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['policy_id'], ['policies.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversations_claim_id'), 'conversations', ['claim_id'], unique=False)
    op.create_index(op.f('ix_conversations_policy_id'), 'conversations', ['policy_id'], unique=False)
    op.create_index(op.f('ix_conversations_user_id'), 'conversations', ['user_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.Enum('user', 'assistant', name='message_role_enum'), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    op.drop_constraint('policies_holder_id_fkey', 'policies', type_='foreignkey')
    op.drop_constraint('policies_vehicle_id_fkey', 'policies', type_='foreignkey')
    op.drop_table('vehicles')
    op.add_column('claims', sa.Column('claimant_id', sa.Uuid(), nullable=False))
    op.add_column('claims', sa.Column('incident_location', sa.String(), nullable=False))
    op.add_column('claims', sa.Column('incident_description', sa.String(), nullable=False))
    op.add_column('claims', sa.Column('claim_type', sa.Enum('own_damage', 'third_party', 'theft', 'natural_calamity', 'fire', name='claim_type_enum'), nullable=False))
    op.add_column('claims', sa.Column('assigned_officer_id', sa.Uuid(), nullable=True))
    op.add_column('claims', sa.Column('ai_risk_score', sa.Float(), nullable=True))
    op.add_column('claims', sa.Column('ai_summary', sa.String(), nullable=True))
    op.add_column('claims', sa.Column('approved_amount', sa.Numeric(precision=12, scale=2), nullable=True))
    op.alter_column('claims', 'status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('draft', 'submitted', 'under_review', 'surveyor_assigned', 'approved', 'rejected', 'settled', 'disputed', name='claim_status_enum'),
               existing_nullable=False,
               postgresql_using="status::claim_status_enum")
    op.alter_column('claims', 'estimated_amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=False)
    op.create_index('idx_claims_policy_status', 'claims', ['policy_id', 'status'], unique=False)
    op.create_index(op.f('ix_claims_assigned_officer_id'), 'claims', ['assigned_officer_id'], unique=False)
    op.create_index(op.f('ix_claims_claimant_id'), 'claims', ['claimant_id'], unique=False)
    op.create_foreign_key(None, 'claims', 'users', ['claimant_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'claims', 'users', ['assigned_officer_id'], ['id'], ondelete='SET NULL')
    op.drop_column('claims', 'description')
    op.add_column('policies', sa.Column('user_id', sa.Uuid(), nullable=False))
    op.add_column('policies', sa.Column('insurer_name', sa.String(length=255), nullable=False))
    op.add_column('policies', sa.Column('vehicle_registration', sa.String(length=100), nullable=False))
    op.add_column('policies', sa.Column('vehicle_make', sa.String(length=100), nullable=False))
    op.add_column('policies', sa.Column('vehicle_model', sa.String(length=100), nullable=False))
    op.add_column('policies', sa.Column('vehicle_year', sa.Integer(), nullable=False))
    op.add_column('policies', sa.Column('policy_type', sa.Enum('comprehensive', 'third_party', 'standalone_od', name='policy_type_enum'), nullable=False))
    op.add_column('policies', sa.Column('sum_insured', sa.Numeric(precision=12, scale=2), nullable=False))
    op.add_column('policies', sa.Column('pdf_storage_path', sa.String(length=500), nullable=True))
    op.add_column('policies', sa.Column('extracted_text', sa.String(), nullable=True))
    op.add_column('policies', sa.Column('embedding_model_version', sa.String(length=100), nullable=True))
    op.alter_column('policies', 'premium_amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=False)
    op.alter_column('policies', 'status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('active', 'expired', 'cancelled', name='policy_status_enum'),
               existing_nullable=False,
               postgresql_using="status::policy_status_enum")
    op.create_index(op.f('ix_policies_user_id'), 'policies', ['user_id'], unique=False)
    op.create_foreign_key(None, 'policies', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('policies', 'holder_id')
    op.drop_column('policies', 'vehicle_id')
    op.drop_column('policies', 'coverage_amount')
    op.add_column('users', sa.Column('phone', sa.String(length=50), nullable=False))
    op.add_column('users', sa.Column('hashed_password', sa.String(length=255), nullable=False))
    op.add_column('users', sa.Column('full_name', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('is_verified', sa.Boolean(), nullable=False))
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('customer', 'insurer_officer', 'advisor', 'aggregator', 'admin', name='user_role_enum'),
               existing_nullable=False,
               postgresql_using="role::user_role_enum")
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('first_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('last_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.alter_column('users', 'role',
               existing_type=sa.Enum('customer', 'insurer_officer', 'advisor', 'aggregator', 'admin', name='user_role_enum'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_column('users', 'is_verified')
    op.drop_column('users', 'full_name')
    op.drop_column('users', 'hashed_password')
    op.drop_column('users', 'phone')
    op.add_column('policies', sa.Column('coverage_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('policies', sa.Column('vehicle_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('policies', sa.Column('holder_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'policies', type_='foreignkey')
    op.create_foreign_key(op.f('policies_vehicle_id_fkey'), 'policies', 'vehicles', ['vehicle_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('policies_holder_id_fkey'), 'policies', 'users', ['holder_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_policies_user_id'), table_name='policies')
    op.alter_column('policies', 'status',
               existing_type=sa.Enum('active', 'expired', 'cancelled', name='policy_status_enum'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('policies', 'premium_amount',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.drop_column('policies', 'embedding_model_version')
    op.drop_column('policies', 'extracted_text')
    op.drop_column('policies', 'pdf_storage_path')
    op.drop_column('policies', 'sum_insured')
    op.drop_column('policies', 'policy_type')
    op.drop_column('policies', 'vehicle_year')
    op.drop_column('policies', 'vehicle_model')
    op.drop_column('policies', 'vehicle_make')
    op.drop_column('policies', 'vehicle_registration')
    op.drop_column('policies', 'insurer_name')
    op.drop_column('policies', 'user_id')
    op.add_column('claims', sa.Column('description', sa.VARCHAR(length=1000), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'claims', type_='foreignkey')
    op.drop_constraint(None, 'claims', type_='foreignkey')
    op.drop_index(op.f('ix_claims_claimant_id'), table_name='claims')
    op.drop_index(op.f('ix_claims_assigned_officer_id'), table_name='claims')
    op.drop_index('idx_claims_policy_status', table_name='claims')
    op.alter_column('claims', 'estimated_amount',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.alter_column('claims', 'status',
               existing_type=sa.Enum('draft', 'submitted', 'under_review', 'surveyor_assigned', 'approved', 'rejected', 'settled', 'disputed', name='claim_status_enum'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_column('claims', 'approved_amount')
    op.drop_column('claims', 'ai_summary')
    op.drop_column('claims', 'ai_risk_score')
    op.drop_column('claims', 'assigned_officer_id')
    op.drop_column('claims', 'claim_type')
    op.drop_column('claims', 'incident_description')
    op.drop_column('claims', 'incident_location')
    op.drop_column('claims', 'claimant_id')
    op.create_table('vehicles',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('owner_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('make', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('model', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('vin', sa.VARCHAR(length=17), autoincrement=False, nullable=False),
    sa.Column('license_plate', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('vehicles_owner_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('vehicles_pkey')),
    sa.UniqueConstraint('vin', name=op.f('vehicles_vin_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_conversations_user_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_policy_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_claim_id'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_claim_images_uploaded_by'), table_name='claim_images')
    op.drop_index(op.f('ix_claim_images_claim_id'), table_name='claim_images')
    op.drop_table('claim_images')
    op.drop_index(op.f('ix_consent_records_user_id'), table_name='consent_records')
    op.drop_table('consent_records')
    op.drop_index(op.f('ix_audit_logs_actor_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_advisor_assignments_customer_id'), table_name='advisor_assignments')
    op.drop_index(op.f('ix_advisor_assignments_advisor_id'), table_name='advisor_assignments')
    op.drop_table('advisor_assignments')

    # Drop enum types explicitly
    postgresql.ENUM(name='user_role_enum').drop(op.get_bind(), checkfirst=True)
    postgresql.ENUM(name='policy_type_enum').drop(op.get_bind(), checkfirst=True)
    postgresql.ENUM(name='policy_status_enum').drop(op.get_bind(), checkfirst=True)
    postgresql.ENUM(name='claim_type_enum').drop(op.get_bind(), checkfirst=True)
    postgresql.ENUM(name='claim_status_enum').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
